### ISSUE TITLE
question about diffusion

### ISSUE THREAD

**Issue by llllly26** [DeepGraphLearning/DiffPack#1]
Hi, i am interested in this paper and focus on the diffusion application of protein structure  prediction. Now, i have a confusion about diffusion model  on side chain packing. the diffusion model can reconstruct the correct angles, sampling noisy angles from prior distribution. if i sampling different noise for the same angles and the same sequence, such as \chi_2， the noise is different,  but the final angles for this sequence should be fixed, different noise can restore the same angles for the sequence? maybe my thought was wrong, i don't understand,  could u please answer to me? thanks!

**Comment by Oxer11** [comment]
Hi, thanks for your interest in our work! Your understanding is correct. For different initial noise, we will generate different angles. Then, we use a confidence model to select the best prediction. For the advantages of generative models over regression models, you can refer to the [DiffDock paper](https://arxiv.org/abs/2210.01776).

**Comment by llllly26** [comment]
> 

oh thanks! the truth is, the generated angles will be different when sampling different noise for the same sequence, this is the same as what i considerd diffusion model. and after this, there is a step that select from these results to get a best prediction. emmm, i have a new question that, 

-  in this way, for a sequence, it needs several times to use diffusion model to generate different angles, and use a confidence model to select the best one ?  instead of just using one time to generate angles? i guess the inference result of one time is: [ generated angles, a confidence score], right? 
- where is the detail of the confidence model, i am sorry that i don't notice it in paper, maybe i ignore it.
thanks!

**Comment by Oxer11** [comment]
1. Yes, your understanding is correct. In principle, the inference result should be [generated angles, a confidence score]. In practice, there may be some differences in the implementation.
2. The confidence model also uses GearNet-Edge as the encoder and an MLP to predict the RMSD. The details of implementation can be found here https://github.com/DeepGraphLearning/DiffPack/blob/81ee51612abfab5af23a8d33fbb081a024f83a1c/diffpack/task.py#L224-L250
The corresponding config is listed here
https://github.com/DeepGraphLearning/DiffPack/blob/81ee51612abfab5af23a8d33fbb081a024f83a1c/config/inference_confidence.yaml#L32-L42

**Comment by llllly26** [comment]
> 1. Yes, your understanding is correct. In principle, the inference result should be [generated angles, a confidence score]. In practice, there may be some differences in the implementation.
> 2. The confidence model also uses GearNet-Edge as the encoder and an MLP to predict the RMSD. The details of implementation can be found here https://github.com/DeepGraphLearning/DiffPack/blob/81ee51612abfab5af23a8d33fbb081a024f83a1c/diffpack/task.py#L224-L250
>    
>    The corresponding config is listed here
>    https://github.com/DeepGraphLearning/DiffPack/blob/81ee51612abfab5af23a8d33fbb081a024f83a1c/config/inference_confidence.yaml#L32-L42

thanks! I will check the code to further enhance my understanding.
