### ISSUE TITLE
Checkpoint files

### ISSUE THREAD

**Issue by abmukho** [DeepGraphLearning/DiffPack#2]
Hi, 
The links to the checkpoint files for both models point to the same file, wondering if that is intended.

Thanks,

**Comment by zytzrh** [comment]
Hi, the checkpoint is indeed the same file. It includes the weight of both diffusion module and confience module. When using different configuration file, the checkpoint will be loaded in different ways - one for vanila DiffPack, and one for DiffPack with confidence selection.
