### ISSUE TITLE
Customized Position Repacking in DiffPack

### ISSUE THREAD

**Issue by YaoYinYing** [DeepGraphLearning/DiffPack#3]
Hi, I really like this project.  

For many protein design tasks with just a few mutations, local repacking around specific positions is more computationally efficient. Can DiffPack repack customized positions while keeping the rest of the structure fixed?

**Comment by zytzrh** [comment]
Hi @YaoYinYing! Thank you for your interest in our project.

While DiffPack is not currently designed for this specific purpose, your suggestion to repack only a few residues while keeping the rest of the structure fixed is akin to conditional sampling within a diffusion model. We find this idea intriguing and worthy of consideration. It could potentially enhance the versatility and utility of DiffPack. We'll take your feedback into account and explore the possibility of adding an interface to support this functionality in the future.
